### ISSUE TITLE
Permissions needed for Run Command incorrect

### ISSUE THREAD

**Issue by meizenga** [MicrosoftDocs/azure-docs.nl-nl#230]
The documentation states that the Contributor role of higer is needed. In fact you need the Virtual Machine Contributor role.
We had users with the Contributor role on Subscription/Resource Group level, but thats not sufficient to use Run Command.
After we also granted the Virtual Machine Contributor role , the users were able to do use the Run Command.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b3ff94e6-3c1f-b9e1-1a46-b75fe2ffca1b
* Version Independent ID: 8f3ca735-ddd4-f4a9-4ee0-189604018784
* Content: [PowerShell-scripts uitvoeren in een Windows-VM in Azure](https://docs.microsoft.com/nl-nl/azure/virtual-machines/windows/run-command)
* Content Source: [articles/virtual-machines/windows/run-command.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/virtual-machines/windows/run-command.md)
* Service: **automation**
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25969](https://github.com/MicrosoftDocs/azure-docs/issues/25969) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @meizenga 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25969

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
