### ISSUE TITLE
AKSAzureADClient should not be 'web', but only works with 'native' type

### ISSUE THREAD

**Issue by TeunRoefs** [MicrosoftDocs/azure-docs.nl-nl#278]
The AKSAzureADClient should be created using the 'legacy' version of the App Registration, or try using the 'Public' variant in the new App Registration.

Using web will cause the authentication to fail.

https://github.com/Azure/AKS/issues/535

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c59648e0-4074-d3ac-8359-cd19745e8c32
* Version Independent ID: f71d012c-2c00-bf17-017c-f144e7e3366e
* Content: [Azure Active Directory integreren met Azure Kubernetes Service](https://docs.microsoft.com/nl-nl/azure/aks/azure-ad-integration#feedback)
* Content Source: [articles/aks/azure-ad-integration.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/aks/azure-ad-integration.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30764](https://github.com/MicrosoftDocs/azure-docs/issues/30764) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @TeunRoefs

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/30764

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
