### ISSUE TITLE
Used geograhies counter intuitive

### ISSUE THREAD

**Issue by vdweij** [MicrosoftDocs/azure-docs.nl-nl#321]
The geography Europe spans regions West Europe and North Europe. The geography name implies the continent Europe or at least a significant part, but there are separate geographies for UK, Germany and France. Confusing naming to say at least...

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 09a788e4-0130-73f2-d985-6fc3aec77974
* Version Independent ID: a9f4ec3f-f0a3-b050-020b-f487c74c5179
* Content: [Zakelijke continuïteit en herstel na noodgevallen (BCDR): Gekoppelde Azure-regio's](https://docs.microsoft.com/nl-nl/azure/best-practices-availability-paired-regions)
* Content Source: [articles/best-practices-availability-paired-regions.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/best-practices-availability-paired-regions.md)
* Service: **multiple**
* GitHub Login: @rayne-wiselman
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31748](https://github.com/MicrosoftDocs/azure-docs/issues/31748) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @vdweij

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/31748

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
