### ISSUE TITLE
Wrong fieldname in script?

### ISSUE THREAD

**Issue by MarkPrinsen48** [MicrosoftDocs/azure-docs.nl-nl#330]
Shouldn't "StrongAuthenticationRequirements" be "StrongAuthenticationMethods"?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 4cb129d2-9594-bf0c-5946-982f0ed0d888
* Version Independent ID: 6522b038-6853-3552-55c8-f174cf56573d
* Content: [Azure multi-factor Authentication gebruikersstatussen - Azure Active Directory](https://docs.microsoft.com/nl-nl/azure/active-directory/authentication/howto-mfa-userstates#feedback)
* Content Source: [articles/active-directory/authentication/howto-mfa-userstates.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/authentication/howto-mfa-userstates.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32259](https://github.com/MicrosoftDocs/azure-docs/issues/32259) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @MarkPrinsen48 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32259

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
