### ISSUE TITLE
Sample code uses ADAL instead of newer MSAL library

### ISSUE THREAD

**Issue by maartenhbe** [MicrosoftDocs/azure-docs.nl-nl#331]
Sample code uses ADAL instead of newer MSAL library, please update.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 692d8637-4033-767b-aa29-3859f301b7b8
* Version Independent ID: de143a26-3dd6-a513-6854-604e4f68c52f
* Content: [ActiveDirectoryInteractive maakt verbinding met SQL](https://docs.microsoft.com/nl-nl/azure/sql-database/active-directory-interactive-connect-azure-sql-db#feedback)
* Content Source: [articles/sql-database/active-directory-interactive-connect-azure-sql-db.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/sql-database/active-directory-interactive-connect-azure-sql-db.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @GithubMirek
* Microsoft Alias: **MirekS**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32039](https://github.com/MicrosoftDocs/azure-docs/issues/32039) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @maartenhbe

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32039

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
