### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by leonmeijer** [MicrosoftDocs/azure-docs.nl-nl#355]
Wasn't able to find "Monitoring and Reports section". It's now the "Monitoring" section.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 04403549-f1f6-6335-ff08-a84bb6c79e75
* Version Independent ID: 91e5132d-ab4c-c4c9-0999-270eac76f587
* Content: [Azure Site Recovery bewaken](https://docs.microsoft.com/nl-nl/azure/site-recovery/site-recovery-monitor-and-troubleshoot#feedback)
* Content Source: [articles/site-recovery/site-recovery-monitor-and-troubleshoot.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/site-recovery/site-recovery-monitor-and-troubleshoot.md)
* Service: **site-recovery**
* GitHub Login: @raynew
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
Hello, @leonmeijer 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32700

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
