### ISSUE TITLE
Warnings when executing this script

### ISSUE THREAD

**Issue by rfcdejong** [MicrosoftDocs/azure-docs.nl-nl#391]
WARNING: Breaking changes in the cmdlet 'Get-AzVirtualNetwork' :
WARNING:  - "The output type 'Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork' is changing"
 - The following properties in the output type are being deprecated :
 'EnableVmProtection'

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 04f5da69-0386-feb0-469a-788ae89d3a3d
* Version Independent ID: 27031537-f436-7252-b73c-7f8edbc176cc
* Content: [Azure PowerShell-voorbeeldscript: een virtuele machine maken op basis van een momentopname](https://docs.microsoft.com/nl-nl/azure/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-snapshot?toc=%2fpowershell%2fmodule%2ftoc.json)
* Content Source: [articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-snapshot.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-create-vm-from-snapshot.md)
* Service: **virtual-machines-windows**
* GitHub Login: @ramankumarlive
* Microsoft Alias: **ramankum**

**Comment by CeciAc** [comment]
Hello, @rfcdejong

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33438

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
