### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by hansthen** [MicrosoftDocs/azure-docs.nl-nl#429]
This documentation lacks crucial information:
1. what is the purpose of this action (from a user's perspective)?
2. what is the result of the actions I will perform?
3. how will the result contribute to my purpose?
4. how can I verify the configuration

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a053a774-e0e7-e7c7-8a08-7244cb0f058d
* Version Independent ID: 7acef172-4c69-6502-d506-c8c3ef13a1c1
* Content: [Doorlopende implementatie met Web App for Containers - Azure App Service](https://docs.microsoft.com/nl-nl/azure/app-service/containers/app-service-linux-ci-cd#feedback)
* Content Source: [articles/app-service/containers/app-service-linux-ci-cd.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/containers/app-service-linux-ci-cd.md)
* Service: **app-service**
* GitHub Login: @msangapu
* Microsoft Alias: **yili**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34490](https://github.com/MicrosoftDocs/azure-docs/issues/34490) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hansthen

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
