### ISSUE TITLE
output?

### ISSUE THREAD

**Issue by bruun963** [MicrosoftDocs/azure-docs.nl-nl#446]
Under step 1 there's an example output of the Keyvault ID, however the output of the 'az storage account show' command only shows the resourceID of the storageaccount, and not the Keyvault ID. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: cebec73e-e7f4-75c5-2068-ae89f12d8d95
* Version Independent ID: e2497a7b-3b5f-554a-1a31-da540740fcc9
* Content: [Opslagaccountsleutels met Azure Key Vault en de Azure CLI beheren](https://docs.microsoft.com/nl-nl/azure/key-vault/key-vault-ovw-storage-keys#feedback)
* Content Source: [articles/key-vault/key-vault-ovw-storage-keys.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/key-vault/key-vault-ovw-storage-keys.md)
* Service: **key-vault**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35177](https://github.com/MicrosoftDocs/azure-docs/issues/35177) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @bruun963

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs.nl-nl/issues/446. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
