### ISSUE TITLE
Ls is missing from the page

### ISSUE THREAD

**Issue by Johannes-Vink** [MicrosoftDocs/azure-docs.nl-nl#448]
Hi, Lsv2 is listed on this page, however the L non v2 has been removed. On the pricing page the L4 is still listed.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b7323e68-7415-ba43-47de-8d1738f7c52b
* Version Independent ID: 1bce47f4-d516-dd38-3e54-8da7b9b7b416
* Content: [Azure Windows VM-grootten - opslag](https://docs.microsoft.com/nl-nl/azure/virtual-machines/windows/sizes-storage#feedback)
* Content Source: [articles/virtual-machines/windows/sizes-storage.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-machines/windows/sizes-storage.md)
* Service: **virtual-machines-windows**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by srvbpigh** [comment]
Hello, @Johannes-Vink
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35328](https://github.com/MicrosoftDocs/azure-docs/issues/35328) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Johannes-Vink

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35328

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
