### ISSUE TITLE
better split of the naming of the two resourcegroups

### ISSUE THREAD

**Issue by bartjanson** [MicrosoftDocs/azure-docs.nl-nl#449]
paragraph Why are two resource groups created with AKS?
describes two, but at the 1) it talks about the first AND the second group:
An example of the second resource group is MC_myResourceGroup_myAKSCluster_eastus. For information on how to specify the name of this second resource group, see the next section.
This should be moved to 2).

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d501ff67-9208-8bcb-e8df-f09e9b16a802
* Version Independent ID: e3fc3851-ddc4-d26c-251d-6ae53d714081
* Content: [Veelgestelde vragen voor Azure Kubernetes Service (AKS)](https://docs.microsoft.com/nl-nl/azure/aks/faq)
* Content Source: [articles/aks/faq.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/aks/faq.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @bartjanson
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @bartjanson

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35333

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
