### ISSUE TITLE
Exclude from baseline policy

### ISSUE THREAD

**Issue by GitTune** [MicrosoftDocs/azure-docs.nl-nl#451]
This article says:  "If you have enabled a baseline policy, you should exclude your emergency access accounts." This was possible earlier, but not anymore….. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: fff5de5d-9a97-73ff-4694-79027720b5c3
* Version Independent ID: 566a8387-bbdd-8e35-13cc-f2d891bd5608
* Content: [Beheerdersaccounts voor Noodtoegang - Azure Active Directory beheren](https://docs.microsoft.com/nl-nl/azure/active-directory/users-groups-roles/directory-emergency-access)
* Content Source: [articles/active-directory/users-groups-roles/directory-emergency-access.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/users-groups-roles/directory-emergency-access.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @GitTune
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35337](https://github.com/MicrosoftDocs/azure-docs/issues/35337) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @GitTune

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/azure-docs/issues/35337

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
