### ISSUE TITLE
Docs not updated

### ISSUE THREAD

**Issue by mregni** [MicrosoftDocs/azure-docs.nl-nl#464]
The docs are not updated since Oct 2018 but it seems that DISTINCT is implemented and should be explained on this page (see following post: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6719531-provide-support-for-distinct)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 65ef452c-ff25-a2ec-feba-5dafa56cb918
* Version Independent ID: 733a3a55-e899-5c1d-9bcc-34c2d7e17d27
* Content: [Aan de slag met SQL-query's in Azure Cosmos DB](https://docs.microsoft.com/nl-nl/azure/cosmos-db/sql-query-getting-started#feedback)
* Content Source: [articles/cosmos-db/sql-query-getting-started.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/cosmos-db/sql-query-getting-started.md)
* Service: **cosmos-db**
* GitHub Login: @timsander1
* Microsoft Alias: **tisande**

**Comment by srvbpigh** [comment]
Hello, @mregni
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35602](https://github.com/MicrosoftDocs/azure-docs/issues/35602) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mregni

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35602

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
