### ISSUE TITLE
Missing APIM Application concept explanation

### ISSUE THREAD

**Issue by erwinkramer** [MicrosoftDocs/azure-docs.nl-nl#538]
Applications are an APIM concept but are never really explained.  

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 2a747c49-faa5-3a76-f397-b3637e9a21f2
* Version Independent ID: 763ccd3f-d811-09e1-2bd9-eaa2235a32fb
* Content: [Azure API Management-terminologie](https://docs.microsoft.com/nl-nl/azure/api-management/api-management-terminology)
* Content Source: [articles/api-management/api-management-terminology.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/api-management/api-management-terminology.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @erwinkramer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39884](https://github.com/MicrosoftDocs/azure-docs/issues/39884) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @erwinkramer 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/39884.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
