### ISSUE TITLE
Receive.js example not working

### ISSUE THREAD

**Issue by rvdheuvel** [MicrosoftDocs/azure-docs.nl-nl#540]
The `recieve.js` code doesn't delete the messages. To fix it, the `ReceiveAndDelete` in `receive.js` in line 11 should be `receiveAndDelete`
 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: dd72fd9d-6bad-5114-e79a-988f463b3598
* Version Independent ID: 33081439-1037-7ea3-6aef-19b1790fe863
* Content: [Over het gebruik van Azure Service Bus-onderwerpen en abonnementen met behulp van Node.js](https://docs.microsoft.com/nl-nl/azure/service-bus-messaging/service-bus-nodejs-how-to-use-topics-subscriptions-new-package)
* Content Source: [articles/service-bus-messaging/service-bus-nodejs-how-to-use-topics-subscriptions-new-package.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/service-bus-messaging/service-bus-nodejs-how-to-use-topics-subscriptions-new-package.md)
* Service: **service-bus-messaging**
* GitHub Login: @axisc
* Microsoft Alias: **aschhab**

**Comment by srvbpigh** [comment]
Hello, @rvdheuvel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rvdheuvel

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40257

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
