### ISSUE TITLE
Old screenshots?

### ISSUE THREAD

**Issue by D3nnisd** [MicrosoftDocs/azure-docs.nl-nl#543]
Hi,

This page seem to have old screenshots. Or is this a new version/theme?

Thanks,

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 89177180-caeb-e2e1-5614-60719f593672
* Version Independent ID: a3352be5-2343-ae87-38d0-32312a62d2b1
* Content: [Schema triggers maken in Azure Data Factory](https://docs.microsoft.com/nl-nl/azure/data-factory/how-to-create-schedule-trigger#feedback)
* Content Source: [articles/data-factory/how-to-create-schedule-trigger.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/data-factory/how-to-create-schedule-trigger.md)
* Service: **data-factory**
* GitHub Login: @djpmsft
* Microsoft Alias: **daperlov**

**Comment by srvbpigh** [comment]
Hello, @D3nnisd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @D3nnisd 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41453

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
