### ISSUE TITLE
Is there a 3.0 package? Microsoft.Azure.AppConfiguration.AspNetCore

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/azure-docs.nl-nl#545]
or does this work for asp core 3.0? https://www.nuget.org/packages/Microsoft.Azure.AppConfiguration.AspNetCore/2.1.0-preview-010380003-1338

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 80b8d3d6-4125-638f-746a-4bbdf0378625
* Version Independent ID: d917d876-79b4-b935-08f0-09ef86038dd7
* Content: [Zelfstudie voor het gebruik van dynamische configuratie van Azure-app-configuratie in een ASP.NET Core-app](https://docs.microsoft.com/nl-nl/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core)
* Content Source: [articles/azure-app-configuration/enable-dynamic-configuration-aspnet-core.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-app-configuration/enable-dynamic-configuration-aspnet-core.md)
* Service: **azure-app-configuration**
* GitHub Login: @lisaguthrie
* Microsoft Alias: **lcozzens**

**Comment by srvbpigh** [comment]
Hello, @wrkettlitz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @wrkettlitz

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42121

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
