### ISSUE TITLE
Risk levels new features

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/azure-docs.nl-nl#546]
Can you add the risk levels for Malicious IP address, Azure AD threat intelligence and Unfamiliar sign-in properties? Or is this relative? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 198f0e69-af2a-8c82-041a-c5ca4126f02f
* Version Independent ID: 4be57788-f1c2-d6d4-b94a-a59350a618a7
* Content: [Detectie van Azure Active Directorye Risico's](https://docs.microsoft.com/nl-nl/azure/active-directory/reports-monitoring/concept-risk-events)
* Content Source: [articles/active-directory/reports-monitoring/concept-risk-events.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/reports-monitoring/concept-risk-events.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by srvbpigh** [comment]
Hello, @BakkerJan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #43222](https://github.com/MicrosoftDocs/azure-docs/issues/43222) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @BakkerJan

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43222

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
