### ISSUE TITLE
Mismatch with code

### ISSUE THREAD

**Issue by nicowitteman** [MicrosoftDocs/azure-docs.nl-nl#549]
Running the code returns a different set of data in the Token Info pane: 
Name, Token Expires, Access token, Id Token, Tenant Id, whereby Name and TenantId are empty

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 90602ccd-184e-bb74-504c-5b06eb8eb4ab
* Version Independent ID: 3d4865d9-f91f-9aeb-16a8-9789e647c068
* Content: [Zelf studie-gebruikers verifiëren in een systeem eigen client toepassing-Azure Active Directory B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/active-directory-b2c-tutorials-desktop-app?tabs=applications)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-tutorials-desktop-app.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/active-directory-b2c-tutorials-desktop-app.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @nicowitteman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nicowitteman 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43514

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
