### ISSUE TITLE
errorcoder 2010 - A task was canceled.

### ISSUE THREAD

**Issue by mhansma** [MicrosoftDocs/azure-docs.nl-nl#553]
I'm getting an errorcode 2010, referencing to this page but the error isn't mentioned here.
Please could you update this.

{
    "errorCode": "2010",
    "message": "A task was canceled.",
    "failureType": "UserError",
    "target": "XML to TSV",
    "details": []
}
![afbeelding](https://user-images.githubusercontent.com/1673484/70046150-b9502780-15c5-11ea-918f-774ffdd74ec7.png)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b57894dd-9bb6-0900-63c5-71c6b902abdf
* Version Independent ID: 048a747c-7ac0-e9a1-2c36-8cdf82cfd143
* Content: [Problemen oplossen Azure Data Factory](https://docs.microsoft.com/nl-nl/azure/data-factory/data-factory-troubleshoot-guide#feedback)
* Content Source: [articles/data-factory/data-factory-troubleshoot-guide.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/data-factory/data-factory-troubleshoot-guide.md)
* Service: **data-factory**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by srvbpigh** [comment]
Hello, @mhansma
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mhansma

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43985

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
