### ISSUE TITLE
The supplied powershell script restarts IAS without warning

### ISSUE THREAD

**Issue by pkoelemij** [MicrosoftDocs/azure-docs.nl-nl#557]
The installer of the NPS Extension (https://www.microsoft.com/en-us/download/details.aspx?id=54688) provides the person installing with a powershell script at "‘c:\Program Files\Microsoft\AzureMfa\Config\AzureMfaNpsExtnConfigSetup.ps1"

The supplied powershell script restarts IAS without any warning. This restart is undocumented. This can cause trouble in production. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 61df48bb-a963-b1f0-8f64-b55d0bd6904c
* Version Independent ID: 677de59f-a222-8905-11c0-a3ac619d8b56
* Content: [RDG integreren met de Azure MFA NPS-extensie-Azure Active Directory](https://docs.microsoft.com/nl-nl/azure/active-directory/authentication/howto-mfa-nps-extension-rdg#feedback)
* Content Source: [articles/active-directory/authentication/howto-mfa-nps-extension-rdg.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/authentication/howto-mfa-nps-extension-rdg.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @pkoelemij
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pkoelemij 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/44473
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
