### ISSUE TITLE
The givenName and surName are not present in output claims

### ISSUE THREAD

**Issue by HWouters** [MicrosoftDocs/azure-docs.nl-nl#560]
I think this is because given_name and family_name are not present in v2.0 tokens:
https://docs.microsoft.com/nl-nl/azure/active-directory/develop/active-directory-optional-claims 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 171f21f0-1c8c-42f9-dbb8-2da1ebc70892
* Version Independent ID: fe1d0a08-231e-5094-2406-1b548cb1174e
* Content: [Aanmelden voor Azure AD met meerdere tenants instellen door aangepast beleid - Azure AD B2C](https://docs.microsoft.com/nl-nl/azure/active-directory-b2c/active-directory-b2c-setup-commonaad-custom?tabs=applications#feedback)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-setup-commonaad-custom.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory-b2c/active-directory-b2c-setup-commonaad-custom.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @HWouters
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @HWouters, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46077. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
