### ISSUE TITLE
Guest accounts (Azure Identity Protection) 

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/azure-docs.nl-nl#562]
Does IPC also work for guest accounts? And if yes, what will be the license requirements? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 665863f8-00aa-155a-aa5d-9dc4254b60d4
* Version Independent ID: b898c3ed-651d-4fb0-814a-62a857082fd3
* Content: [Veelgestelde vragen over identiteits beveiliging in Azure Active Directory](https://docs.microsoft.com/nl-nl/azure/active-directory/identity-protection/troubleshooting-identity-protection-faq)
* Content Source: [articles/active-directory/identity-protection/troubleshooting-identity-protection-faq.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/active-directory/identity-protection/troubleshooting-identity-protection-faq.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @BakkerJan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @BakkerJan, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46226. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
