### ISSUE TITLE
Access token expiration

### ISSUE THREAD

**Issue by kwaazaar** [MicrosoftDocs/azure-docs.nl-nl#565]
What if the accesstoken expires?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 31b0d33c-f88e-d50c-2926-7933940f3b92
* Version Independent ID: 4aaef906-f501-6947-5d23-1b704470f09d
* Content: [Zelf studie: toegang tot gegevens met beheerde identiteit](https://docs.microsoft.com/nl-nl/azure/app-service/app-service-web-tutorial-connect-msi)
* Content Source: [articles/app-service/app-service-web-tutorial-connect-msi.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/app-service-web-tutorial-connect-msi.md)

**Comment by srvbpigh** [comment]
Hello, @kwaazaar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47696](https://github.com/MicrosoftDocs/azure-docs/issues/47696) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @kwaazaar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47696. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
