### ISSUE TITLE
Change Set-AzWebApp to Set-AzAppServicePlan

### ISSUE THREAD

**Issue by SteveVaneeckhout** [MicrosoftDocs/azure-docs.nl-nl#567]
In the Script explanation section the command Set-AzWebApp is listed but is not actually used in the sample. This should be changed to Set-AzAppServicePlan.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ae4830a1-db43-d02c-6c67-fd314c3871d2
* Version Independent ID: 1889f1e5-a6cb-1c4c-7565-39af8bf651c8
* Content: [Power shell: een web-app hand matig schalen](https://docs.microsoft.com/nl-nl/azure/app-service/scripts/powershell-scale-manual?toc=%2Fpowershell%2Fmodule%2Ftoc.json#feedback)
* Content Source: [articles/app-service/scripts/powershell-scale-manual.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/scripts/powershell-scale-manual.md)
* GitHub Login: @msangapu-msft
* Microsoft Alias: **msangapu**

**Comment by srvbpigh** [comment]
Hello, @SteveVaneeckhout
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49976](https://github.com/MicrosoftDocs/azure-docs/issues/49976) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @SteveVaneeckhout, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/49976. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
