### ISSUE TITLE
Variables used in the pseudo code template

### ISSUE THREAD

**Issue by verbedr** [MicrosoftDocs/azure-docs.nl-nl#576]
In the template pseudo code there is a reference to 'storageConnectionStringName' and 'storageConnectionStringResourceId' what is the difference and could someone add an example?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7feaa3d0-7233-a3cb-cb9b-a9a55b1f0d7a
* Version Independent ID: f41f9d51-52f8-1f45-1043-1344a3b74458
* Content: [Key Vault verwijzingen gebruiken](https://docs.microsoft.com/nl-nl/azure/app-service/app-service-key-vault-references)
* Content Source: [articles/app-service/app-service-key-vault-references.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/app-service-key-vault-references.md)
* GitHub Login: @mattchenderson
* Microsoft Alias: **mahender**

**Comment by srvbpigh** [comment]
Hello, @verbedr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50046](https://github.com/MicrosoftDocs/azure-docs/issues/50046) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @verbedr, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50046. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
