### ISSUE TITLE
add limits forManagement Groups

### ISSUE THREAD

**Issue by dvherk** [MicrosoftDocs/azure-docs.nl-nl#578]
please the Management Groups as a seperate paragraph (above subscription limits?). Input from this page can be used; https://docs.microsoft.com/en-us/azure/governance/management-groups/overview 
Please add also if there are limits to the number of subscriptions per MG etc...

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 36f49a06-90b1-cbe1-3853-2c38277b79f8
* Version Independent ID: 02ff6f6c-3ef6-b48f-060d-b290419e0aba
* Content: [Limieten en quota voor Azure-abonnementen](https://docs.microsoft.com/nl-nl/azure/azure-resource-manager/management/azure-subscription-service-limits#general-limits)
* Content Source: [articles/azure-resource-manager/management/azure-subscription-service-limits.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-resource-manager/management/azure-subscription-service-limits.md)

**Comment by srvbpigh** [comment]
Hello, @dvherk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @dvherk, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50440. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
