### ISSUE TITLE
how about mac software

### ISSUE THREAD

**Issue by WillemVerwijs** [MicrosoftDocs/azure-docs.nl-nl#579]
We have some of those non professionals who use Eppul Mek (or however you write that). Is there a client for those lo...s and cloud you also make a link available to that software. prio:... well. low? or is that too high?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 524e47b0-1295-7d07-0cbc-86e6daaa1358
* Version Independent ID: 1cb3a5d8-4f16-583c-ad85-325f7638a873
* Content: [Verbinding maken met Windows Virtual Desktop Windows 10 of 7-Azure](https://docs.microsoft.com/nl-nl/azure/virtual-desktop/connect-windows-7-and-10)
* Content Source: [articles/virtual-desktop/connect-windows-7-and-10.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/virtual-desktop/connect-windows-7-and-10.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @WillemVerwijs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @WillemVerwijs, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50510. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
