### ISSUE TITLE
--attach-acr does not work for AKS cluster with MSI

### ISSUE THREAD

**Issue by aristosvo** [MicrosoftDocs/azure-docs.nl-nl#585]
`az aks update -n testmsi -g aks-rg --attach-acr testmsi` failed with `Could not create a role assignment for ACR. Are you an Owner on this subscription?`

Cluster is created with command `az aks create -g aks-rg -n testmsi --enable-managed-identity`

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ed59d472-ac33-5c03-dbb7-0e86e88c7dd8
* Version Independent ID: 69e1ad8c-2dd3-cc1b-2b31-996a5d866cc0
* Content: [Azure-containerregister integreren met Azure Kubernetes-service](https://docs.microsoft.com/nl-nl/azure/aks/cluster-container-registry-integration)
* Content Source: [articles/aks/cluster-container-registry-integration.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/aks/cluster-container-registry-integration.md)

**Comment by srvbpigh** [comment]
Hello, @aristosvo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51672](https://github.com/MicrosoftDocs/azure-docs/issues/51672) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @aristosvo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51672. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
