### ISSUE TITLE
Key rotation using Azure Automation warning

### ISSUE THREAD

**Issue by rbnmk** [MicrosoftDocs/azure-docs.nl-nl#586]
I believe this warning is not accurate anymore since I am using the AZ module in my Automation account runbooks.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1e31ea14-f6b0-0cd8-0aee-64427a665a36
* Version Independent ID: 60879db1-8dff-b97b-3051-c129181f1c97
* Content: [Azure Key Vault instellen met end-to-end sleutelrotatie en -controle](https://docs.microsoft.com/nl-nl/azure/key-vault/key-vault-key-rotation-log-monitoring#feedback)
* Content Source: [articles/key-vault/key-vault-key-rotation-log-monitoring.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/key-vault/key-vault-key-rotation-log-monitoring.md)
* Service: **key-vault**
* Sub-service: **secrets**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by rbnmk** [comment]
I am of course talking about the Powershell AzureRM module warning

**Comment by srvbpigh** [comment]
Hello, @rbnmk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51921](https://github.com/MicrosoftDocs/azure-docs/issues/51921) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @rbnmk, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51921. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
