### ISSUE TITLE
Link to  Azure-plug-in voor dynamische voorraad.

### ISSUE THREAD

**Issue by riemers** [MicrosoftDocs/azure-docs.nl-nl#587]
Link to the azure plugin is a 404. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d2b8e92b-a339-3869-9c78-e99cb04b94ee
* Version Independent ID: f26cb51b-3a0f-ff82-1b92-03084b52fd56
* Content: [Zelfstudie - Dynamische inventarissen van uw Azure-resources configureren met Ansible](https://docs.microsoft.com/nl-nl/azure/ansible/ansible-manage-azure-dynamic-inventories)
* Content Source: [articles/ansible/ansible-manage-azure-dynamic-inventories.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/ansible/ansible-manage-azure-dynamic-inventories.md)

**Comment by srvbpigh** [comment]
Hello, @riemers
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52184](https://github.com/MicrosoftDocs/azure-docs/issues/52184) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @riemers, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52184. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
