### ISSUE TITLE
Single application or multiple

### ISSUE THREAD

**Issue by erwinkramer** [MicrosoftDocs/azure-docs.nl-nl#588]
So the text is: "running only a single customer's applications", did you really mean to say applications (plural) or application?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: af931817-c3c8-6376-d2c2-a10795161d04
* Version Independent ID: d2b59e0c-0c35-a335-b523-64f4d6f29d09
* Content: [Inleiding](https://docs.microsoft.com/nl-nl/azure/app-service/environment/intro#feedback)
* Content Source: [articles/app-service/environment/intro.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/app-service/environment/intro.md)
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by srvbpigh** [comment]
Hello, @erwinkramer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52409](https://github.com/MicrosoftDocs/azure-docs/issues/52409) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @erwinkramer, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52409. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
