### ISSUE TITLE
False cli command: "az deployment group" should read: "az group deployment"

### ISSUE THREAD

**Issue by GeorgeWieggers** [MicrosoftDocs/azure-docs.nl-nl#591]
Please fix this page.

The command: az deployment group
Should read: az group deployment

Thank you!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6a9c195d-22dc-a381-dedd-b829d6a3e82f
* Version Independent ID: eed3f4f4-98b3-f47e-07d4-d146085cfc68
* Content: [Het implementatie quotum is overschreden](https://docs.microsoft.com/nl-nl/azure/azure-resource-manager/templates/deployment-quota-exceeded#feedback)
* Content Source: [articles/azure-resource-manager/templates/deployment-quota-exceeded.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/azure-resource-manager/templates/deployment-quota-exceeded.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @GeorgeWieggers
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54943](https://github.com/MicrosoftDocs/azure-docs/issues/54943) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @GeorgeWieggers, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54943. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
