### ISSUE TITLE
Incorrect setting mentioned

### ISSUE THREAD

**Issue by timvanderweijde** [MicrosoftDocs/azure-docs.nl-nl#603]
[Voer hier feedback in]
Connection draining helps you gracefully remove back-end pool members during planned service updates. **You can apply this setting to all members of a back-end pool during rule creation.** 

This is incorrect. You can provide the connection drain setting on creation of a HTTPSetting.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 166e6517-9190-c9fc-5ad5-757ad64bb3fc
* Version Independent ID: 0e67beb9-827a-cafb-b0aa-6d38d32475f4
* Content: [Overzicht van Azure-toepassing gateway configuratie](https://docs.microsoft.com/nl-nl/azure/application-gateway/configuration-overview#connection-draining)
* Content Source: [articles/application-gateway/configuration-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/master/articles/application-gateway/configuration-overview.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **absha**

**Comment by srvbpigh** [comment]
Hello, @timvanderweijde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #57177](https://github.com/MicrosoftDocs/azure-docs/issues/57177) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @timvanderweijde, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/57177. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
