### ISSUE TITLE
Configure different webroot

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#79]
Usually index.php doesn't live in the document root of a git project, but in a directory like html, public or web. I would appreciate a quick hint on how to configure the webapp to use this directory. I am sure this information lives somewhere, but I would really appreciate a quick hint on this page also.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ef971d21-e72b-7771-d34a-b6da42d602bb
* Version Independent ID: f60dc748-8cf9-a8eb-9b96-e30cd13acc56
* Content: [Een PHP-web-app maken en implementeren in App Service on Linux](https://docs.microsoft.com/nl-nl/azure/app-service/containers/quickstart-php#create)
* Content Source: [articles/app-service/containers/quickstart-php.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/app-service/containers/quickstart-php.md)
* Service: **app-service-web**
* GitHub Login: @SyntaxC4
* Microsoft Alias: **cfowler**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14289](https://github.com/MicrosoftDocs/azure-docs/issues/14289) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @bartmcleod 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14289.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
