### ISSUE TITLE
Typo in command

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#86]
The command `sudo -i blkid` is wrong it should be `sudo blkid`

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 2036c044-4fbd-6016-c026-fea724b530d6
* Version Independent ID: dde369ae-7a34-0753-5dfe-3720bf69e996
* Content: [Een gegevensschijf toevoegen voor Linux-VM met de Azure CLI](https://docs.microsoft.com/nl-nl/azure/virtual-machines/linux/add-disk?toc=%2fazure%2fvirtual-machines%2flinux%2ftoc.json)
* Content Source: [articles/virtual-machines/linux/add-disk.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/virtual-machines/linux/add-disk.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14956](https://github.com/MicrosoftDocs/azure-docs/issues/14956) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @bartmcleod 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - **https://github.com/MicrosoftDocs/azure-docs/issues/14956**

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
