### ISSUE TITLE
Programming languages

### ISSUE THREAD

**Issue by samvruggink** [MicrosoftDocs/azure-docs.nl-nl#90]
Since the recent function apps update there is only support for C#, Javascript and Java (preview). This article still says it supports  C#, F#, Node.js, Java and PHP. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a8a0ac96-e410-b481-9fdb-90d827a98935
* Version Independent ID: 6a133cdf-a66a-9807-d431-2e0ae43b253b
* Content: [Overzicht van Azure Functions](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-overview)
* Content Source: [articles/azure-functions/functions-overview.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/functions-overview.md)
* Service: **functions**
* GitHub Login: @mattchenderson
* Microsoft Alias: **glenga**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16601](https://github.com/MicrosoftDocs/azure-docs/issues/16601) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @samvruggink 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/16601.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
