### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by CentricStraaten** [MicrosoftDocs/azure-docs.nl-nl#92]
I copied the code to test this pattern. It compiles local and can published online without any problems. When I call the function as documented I receive a 404 HttpResponse. In the log files I notice and exception:  The function 'HandleFile' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the active orchestrator functions: 'E2_BackupSiteContent'.. InstanceId: ac0cc5f9e844461e9b1431f32e24f8b6. Function: HandleFile. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.6.2. SequenceNumber

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 2cc3cf42-8395-7e45-ae2e-6c629576d4f6
* Version Independent ID: 6e60aa29-d501-270c-9e52-53138a0cf547
* Content: [Fan-uitgaand/fan-in scenario's in duurzame functies - Azure](https://docs.microsoft.com/nl-nl/azure/azure-functions/durable-functions-cloud-backup)
* Content Source: [articles/azure-functions/durable-functions-cloud-backup.md](https://github.com/MicrosoftDocs/azure-docs.nl-nl/blob/live/articles/azure-functions/durable-functions-cloud-backup.md)
* Service: **azure-functions**
* GitHub Login: @cgillum
* Microsoft Alias: **azfuncdf**

**Comment by cgillum** [comment]
This is most likely because the host.json file you're using does not match the host.json file used by the samples: [host.json](https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/host.json).

Assuming this is your problem, we mentioned this in the previous chaining sample, but we probably need to add the clarification here as well.

**Comment by LisandroSu** [comment]
Hello, @cgillum 

Thanks for the answer! Should we move this issue to the ENU repo? Let us know when we can close it.

Thanks again!

**Comment by cgillum** [comment]
I'm not familiar with the repositories used by MicrosoftDocs, but this issue is indeed language agnostic.

**Comment by LisandroSu** [comment]
Usually with issues like this, we send it to the source repo for fixing. But if you are working on the issue we can close it and you can let the user know when it's fixed.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17347](https://github.com/MicrosoftDocs/azure-docs/issues/17347) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @cgillum,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/17347.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
